name: spellcheck 
on:
  workflow_call:
    secrets:
      RESUSABLE_GH_ACTION_TOKEN:
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: spellcheck checkout
       uses: actions/checkout@v2
     - name: Spellcheck workflow help
       run: |
         echo "Please refer spellcheck help text file https://github.com/devonfw/.github/blob/master/SPELLCHECK_HELP.asciidoc "
         echo "Do necessary steps as mentioned to fix your workflow."
     - name: download spellcheck config file
       run: |
        wget https://raw.githubusercontent.com/devonfw/.github/master/.github/workflows/.spellcheck.yml -O ./.spellcheck.yml
     - name: download dictionary
       run: |
        wget https://raw.githubusercontent.com/devonfw/.github/master/en-devonfw.dict -O ./en-devonfw.dict
     - uses: igsekor/pyspelling-any@v0.0.2
       name: Spellcheck
